name: Third Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a  
        #   lsfgf -a
      #- uses: actions/checkout@v4
      - uses: actions/checkout
      - name: List Files
        run: |
          ls -a 
